org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
forge_version=47.4.10
mod_id=epicfight_posture_integration
mod_name=Epic Fight Posture Integration
mod_version=1.0.0
mod_group_id=dev.nire9734.epicfightposture
mod_authors=nire9734
mod_license=GPL-3.0-only

# CurseForge file IDs used by CurseMaven
epic_fight_project=405076
epic_fight_file=8049910
combat_evolution_project=1377795
combat_evolution_file=8699861
